<?xml version="1.0" encoding="UTF-8"?>
<ivntTest xmlns="http://www.aria-networks.com">

	<ivntTestVersion>1.0</ivntTestVersion>

	<documentCreated>Mon Dec 12 10:20:42 2016</documentCreated>

	<testScript>
		<name><![CDATA[<unnamed>]]></name>
		<description><![CDATA[<New Script>]]></description>
		<version><![CDATA[]]></version>
		<script><![CDATA[include "js_test_init.js"
include "autoTestPaths.js"
include "autoUtils.js"
include "test_A0267_Export_and_import_as_XLSX_file.js"

var g_outFile = "jsunit_default.xml";

TestSuiteA0267_Export_and_import_as_XLSX_file();]]></script>
		<expanded>false</expanded>
	</testScript>
	<help><![CDATA[]]></help>
</ivntTest>
